"""Added note column to UserSneaker

Revision ID: 885695d0ad28
Revises: 3c6806c1db87
Create Date: 2023-12-31 15:53:02.045623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '885695d0ad28'
down_revision = '3c6806c1db87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sneakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sneakers', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
